In [1]:
#13.1

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston

In [3]:
boston = load_boston()
features = boston.data[:,0:2]
target = boston.target

In [4]:
regression = LinearRegression()

In [5]:
model = regression.fit(features, target)

In [6]:
model.intercept_


22.485628113468223

In [7]:
model.coef_

array([-0.35207832,  0.11610909])

In [8]:
target[0]*1000

24000.0

In [9]:
model.predict(features)[0]*1000

24573.366631705547

In [10]:
model.coef_[0]*1000

-352.07831564026765

In [11]:
#13.2

In [12]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.preprocessing import PolynomialFeatures

In [13]:
boston = load_boston()
features = boston.data[:,0:2]
target = boston.target

In [14]:
interaction = PolynomialFeatures(
 degree=3, include_bias=False, interaction_only=True)
features_interaction = interaction.fit_transform(features)

In [15]:
regression = LinearRegression()

In [16]:
model = regression.fit(features_interaction, target)

In [17]:
features[0]

array([6.32e-03, 1.80e+01])

In [18]:
import numpy as np

In [19]:
interaction_term = np.multiply(features[:, 0], features[:, 1])

In [20]:
interaction_term[0]

0.11376

In [21]:
features_interaction[0]

array([6.3200e-03, 1.8000e+01, 1.1376e-01])

In [22]:
#13.3

In [23]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.preprocessing import PolynomialFeatures

In [24]:
boston = load_boston()
features = boston.data[:,0:1]
target = boston.target

In [25]:
polynomial = PolynomialFeatures(degree=3, include_bias=False)
features_polynomial = polynomial.fit_transform(features)

In [26]:
regression = LinearRegression()

In [27]:
model = regression.fit(features_polynomial, target)

In [28]:
features[0]

array([0.00632])

In [29]:
features[0]**2

array([3.99424e-05])

In [30]:
features[0]**3

array([2.52435968e-07])

In [31]:
features_polynomial[0]

array([6.32000000e-03, 3.99424000e-05, 2.52435968e-07])

In [32]:
#13.4

In [33]:
from sklearn.linear_model import Ridge
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler

In [34]:
boston = load_boston()
features = boston.data
target = boston.target

In [35]:
scaler = StandardScaler()

In [36]:
features_standardized = scaler.fit_transform(features)

In [37]:
regression = Ridge(alpha=0.5)

In [38]:
model = regression.fit(features_standardized, target)

In [39]:
from sklearn.linear_model import RidgeCV

In [40]:
regr_cv = RidgeCV(alphas=[0.1, 1.0, 10.0])

In [41]:
model_cv = regr_cv.fit(features_standardized, target)

In [42]:
model_cv.coef_


array([-0.91987132,  1.06646104,  0.11738487,  0.68512693, -2.02901013,
        2.68275376,  0.01315848, -3.07733968,  2.59153764, -2.0105579 ,
       -2.05238455,  0.84884839, -3.73066646])

In [43]:
model_cv.alpha_

1.0

In [44]:
#13.5

In [45]:
from sklearn.linear_model import Lasso
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler

In [46]:
boston = load_boston()

In [47]:
features = boston.data
target = boston.target

In [48]:
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

In [49]:
regression = Lasso(alpha=0.5)

In [50]:
model = regression.fit(features_standardized, target)

In [51]:
model.coef_

array([-0.11526463,  0.        , -0.        ,  0.39707879, -0.        ,
        2.97425861, -0.        , -0.17056942, -0.        , -0.        ,
       -1.59844856,  0.54313871, -3.66614361])

In [52]:
regression_a10 = Lasso(alpha=10)
model_a10 = regression_a10.fit(features_standardized, target)
model_a10.coef_

array([-0.,  0., -0.,  0., -0.,  0., -0.,  0., -0., -0., -0.,  0., -0.])