In [1]:
#18.1
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

In [2]:
iris = datasets.load_iris()
features = iris.data
target = iris.target

In [3]:
classifer = GaussianNB()

In [4]:
model = classifer.fit(features, target)

In [5]:
new_observation = [[ 4, 4, 4, 0.4]]

In [6]:
model.predict(new_observation)

array([1])

In [7]:
clf = GaussianNB(priors=[0.25, 0.25, 0.5])

In [8]:
model = classifer.fit(features, target)

In [9]:
#18.2
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
text_data = np.array(['I love Brazil. Brazil!',
 'Brazil is best',
'Germany beats both'])
count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)
features = bag_of_words.toarray()
target = np.array([0,0,1])
classifer = MultinomialNB(class_prior=[0.25, 0.5])
model = classifer.fit(features, target)

In [11]:
new_observation = [[0, 0, 0, 1, 0, 1, 0]]
model.predict(new_observation)

array([0])

In [12]:
#18.3
import numpy as np
from sklearn.naive_bayes import BernoulliNB

In [13]:
features = np.random.randint(2, size=(100, 3))
target = np.random.randint(2, size=(100, 1)).ravel()
classifer = BernoulliNB(class_prior=[0.25, 0.5])

In [14]:
model = classifer.fit(features, target)

In [15]:
model_uniform_prior = BernoulliNB(class_prior=None, fit_prior=True)

In [16]:
#18.4
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.calibration import CalibratedClassifierCV

In [17]:
iris = datasets.load_iris()
features = iris.data
target = iris.target

In [18]:
classifer = GaussianNB()

In [19]:
classifer_sigmoid = CalibratedClassifierCV(classifer, cv=2, method='sigmoid')

In [20]:
classifer_sigmoid.fit(features, target)

CalibratedClassifierCV(base_estimator=GaussianNB(), cv=2)

In [21]:
new_observation = [[ 2.6, 2.6, 2.6, 0.4]]

In [22]:
classifer_sigmoid.predict_proba(new_observation)

array([[0.31859969, 0.63663466, 0.04476565]])

In [23]:
classifer.fit(features, target).predict_proba(new_observation)

array([[2.31548432e-04, 9.99768128e-01, 3.23532277e-07]])

In [24]:
classifer_sigmoid.predict_proba(new_observation)

array([[0.31859969, 0.63663466, 0.04476565]])